version: '3.8'
services:
  recorder-backend:
    build:
      context: ./recorder-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # MySQL connection
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/recorder
      SPRING_DATASOURCE_USERNAME: youruser
      SPRING_DATASOURCE_PASSWORD: yourpass

      # These pick up the Dockerfile’s ENV defaults if you don’t override
      APP_LOG_PATH: /app/logs/application.log
      APP_FILE_PATH: /app/uploaded_files
    volumes:
      - /Users/baomini/market_pulse/backend/applog:/app/logs
      - /Users/baomini/market_pulse/backend/uploaded_files:/app/uploaded_files
    restart: unless-stopped
